site_name: STACK
extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
theme:
    name: bootstrap
    custom_dir: overrides
    logo: img/logo_large.svg
    
#custom_css:
#    - /overrides/custom.css

markdown_extensions:
    - mdx_math
nav:
    - Home: 'index.md'
    - About: 'About.md'
    - Get Started: 'GetStarted.md'
    - Training and Events: 'Training_and_events.md'
    - Case Studies:
        - 2019:
            - 'CaseStudies/2019/index.md'
            - 'CaseStudies/2019/FAC.md'
            - 'CaseStudies/2019/PhysicsCurriculum.md'
            - 'CaseStudies/2019/Adaptive.md'
            - 'CaseStudies/2019/FlickInterface.md'
            - 'CaseStudies/2019/Maseno.md'
            - 'CaseStudies/2019/optes.md'
            - 'CaseStudies/2019/ILIAS.md'
            - 'CaseStudies/2019/StackAtScale.md'
            - 'CaseStudies/2019/ABACUS.md'
            - 'CaseStudies/2019/Loughborough.md'
            - 'CaseStudies/2019/Edinburgh.md'
    - Documentation: 'https://stack-test.readthedocs.io/en/latest/'