site_name: Malthe's docs
extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

#theme: readthedocs

markdown_extensions:
    - mdx_math
include_sidebar: false
    
nav:
    - Home: 'index.md'
    - About: 'About.md'
    - Training and Events: 'Training_and_events.md'
    - Case Studies:
        - 2019:
        - 2020: 
    - FAQ: 'FAQ.md'
    - Contact: 'Contact.md'
    - Docs: 'https://stack-test.readthedocs.io/en/latest/'